# Generated by Django 4.1.2 on 2022-10-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_userorder_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='table',
            field=models.IntegerField(),
        ),
    ]
