# Generated by Django 4.1.2 on 2022-10-16 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_userorder_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorder',
            name='table',
        ),
    ]
