# Generated by Django 4.1.2 on 2022-10-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_table_userorder_table_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_number',
            field=models.TextField(),
        ),
    ]
