# Generated by Django 4.1.2 on 2022-10-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_allergens'),
    ]

    operations = [
        migrations.AddField(
            model_name='salad',
            name='dish_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
