# Generated by Django 4.1.2 on 2022-10-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_salad_dish_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='salad',
            name='allergies',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
