# Generated by Django 4.1.2 on 2022-10-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_salad_allergies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='table_number',
            field=models.IntegerField(),
        ),
    ]
