# Generated by Django 4.1.2 on 2022-10-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_alter_userorder_table_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllDaySnacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=200)),
                ('dish_description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': 'List of All Day Snacks',
                'verbose_name_plural': 'List of All Day Snacks',
            },
        ),
    ]
