# Generated by Django 4.1.2 on 2022-10-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_alldaysnacks'),
    ]

    operations = [
        migrations.AddField(
            model_name='toppings',
            name='dish_name',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
