# Generated by Django 4.1.2 on 2022-10-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_burgers_desserts_maindishes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraToppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping_name', models.CharField(max_length=200)),
                ('dish_name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': 'List of Extra Toppings',
                'verbose_name_plural': 'List of Extra Toppings',
            },
        ),
    ]
