# Generated by Django 4.1.2 on 2022-10-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_salad_dish_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salad',
            name='dish_image',
            field=models.CharField(default='media/media/no-img-available.png', max_length=200),
        ),
    ]
