# Generated by Django 4.1.2 on 2022-11-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_alter_salad_dish_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='alldaysnacks',
            name='allergies',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='burgers',
            name='allergies',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='desserts',
            name='allergies',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='maindishes',
            name='allergies',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='salad',
            name='allergies',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
