# Generated by Django 4.1.2 on 2022-11-05 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_alldaysnacks_allergies_burgers_allergies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salad',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.category'),
        ),
    ]
