# Generated by Django 4.1.2 on 2022-11-05 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_salad_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='alldaysnacks',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.category'),
        ),
    ]
