# Generated by Django 4.1.2 on 2022-11-05 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_alldaysnacks_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='burgers',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.category'),
        ),
        migrations.AddField(
            model_name='desserts',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.category'),
        ),
        migrations.AddField(
            model_name='maindishes',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.category'),
        ),
    ]
