# Generated by Django 4.1.2 on 2022-11-05 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_burgers_category_id_desserts_category_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DinnerPlatters',
        ),
        migrations.DeleteModel(
            name='ExtraToppings',
        ),
        migrations.DeleteModel(
            name='Pasta',
        ),
        migrations.DeleteModel(
            name='RegularPizza',
        ),
        migrations.DeleteModel(
            name='SicilianPizza',
        ),
        migrations.DeleteModel(
            name='Sub',
        ),
        migrations.DeleteModel(
            name='Toppings',
        ),
    ]
