# Generated by Django 4.1.2 on 2022-11-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_delete_dinnerplatters_delete_extratoppings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alldaysnacks',
            name='dish_image',
            field=models.CharField(default='media/media/no-img-available.png', max_length=200),
        ),
    ]
