# Generated by Django 4.1.2 on 2022-11-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_alldaysnacks_dish_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='burgers',
            name='dish_image',
            field=models.CharField(default='media/media/no-img-available.png', max_length=200),
        ),
        migrations.AddField(
            model_name='desserts',
            name='dish_image',
            field=models.CharField(default='media/media/no-img-available.png', max_length=200),
        ),
        migrations.AddField(
            model_name='maindishes',
            name='dish_image',
            field=models.CharField(default='media/media/no-img-available.png', max_length=200),
        ),
    ]
