# Generated by Django 4.1.2 on 2022-11-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_salad_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='alldaysnacks',
            name='enabled',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='burgers',
            name='enabled',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='desserts',
            name='enabled',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maindishes',
            name='enabled',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
