# Generated by Django 4.1.2 on 2022-11-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_alldaysnacks_enabled_burgers_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_gif',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_title',
        ),
        migrations.AddField(
            model_name='category',
            name='category_title_el',
            field=models.CharField(default=None, max_length=200, verbose_name='category_title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='category_title_en',
            field=models.CharField(default=None, max_length=200, verbose_name='category_title'),
            preserve_default=False,
        ),
    ]
