# Generated by Django 4.1.2 on 2022-11-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_salad_dish_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salad',
            name='dish_image2',
        ),
        migrations.AlterField(
            model_name='salad',
            name='dish_image',
            field=models.ImageField(default='media/no-img-available.png', upload_to='salads'),
        ),
    ]
