# Generated by Django 4.1.2 on 2022-11-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_remove_salad_dish_image2_alter_salad_dish_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alldaysnacks',
            name='dish_image',
            field=models.ImageField(default='media/no-img-available.png', upload_to='salads'),
        ),
        migrations.AlterField(
            model_name='burgers',
            name='dish_image',
            field=models.ImageField(default='media/no-img-available.png', upload_to='salads'),
        ),
        migrations.AlterField(
            model_name='desserts',
            name='dish_image',
            field=models.ImageField(default='media/no-img-available.png', upload_to='salads'),
        ),
        migrations.AlterField(
            model_name='maindishes',
            name='dish_image',
            field=models.ImageField(default='media/no-img-available.png', upload_to='salads'),
        ),
    ]
