# Generated by Django 4.1.2 on 2022-11-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0040_alter_alldaysnacks_dish_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alldaysnacks',
            name='dish_image',
            field=models.ImageField(default='media/no-img-available.png', upload_to='snacks'),
        ),
        migrations.AlterField(
            model_name='burgers',
            name='dish_image',
            field=models.ImageField(default='media/no-img-available.png', upload_to='burgers'),
        ),
        migrations.AlterField(
            model_name='desserts',
            name='dish_image',
            field=models.ImageField(default='media/no-img-available.png', upload_to='desserts'),
        ),
        migrations.AlterField(
            model_name='maindishes',
            name='dish_image',
            field=models.ImageField(default='media/no-img-available.png', upload_to='mains'),
        ),
    ]
